version: '3'
services:
  db:
    image: mysql:5.7
    container_name: Sonic_mysql_db
    restart: always                       
    environment:
      MYSQL_DATABASE: 'database'              
      MYSQL_USER: 'user'                
      MYSQL_PASSWORD: 'password'          
      MYSQL_ROOT_PASSWORD: 'password'       
    ports:
      - '3306:3306'                       
    volumes:
      - database:/var/lib/mysql
  frontend:
    build: 
      context : ./epresence_frontend
      dockerfile: dockerfile
    container_name: Sonic_frontend
    command: sh -c "npm start"
    restart: always  
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  backend:
    build: 
      context: ./sonic
      dockerfile: dockerfile
    container_name: Sonic_backend
    command: sh -c "DJANGO_SUPERUSER_PASSWORD=admin \ DJANGO_SUPERUSER_USERNAME=admin \ DJANGO_SUPERUSER_EMAIL=admin@domain.com \ python3 manage.py createsuperuser \ --no-input || python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  database: