version: '3'
services:
  frontend:
    build: 
      context : ./epresence_frontend
      dockerfile: dockerfile
    container_name: Sonic_frontend
    command: bash -c "npm start"
    restart: always
    volumes:
      - ./epresence_frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: ./sonic
      dockerfile: dockerfile
    container_name: Sonic_backend
    command: bash -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./sonic:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
volumes:
  data: