version: '3'
services:
  db:
    image: mysql:5.7
    container_name: Sonic_mysql_db
    restart: always                       
    environment:
      MYSQL_DATABASE: 'test'              
      MYSQL_USER: 'sample'                
      MYSQL_PASSWORD: 'password'          
      MYSQL_ROOT_PASSWORD: 'password'     
    ports:
      - '3306:3306'                       
    expose:
      - '3306'
    volumes:
      - mysql-db-5.7:/var/lib/mysql
  frontend:
    build: 
      context : ./epresence_frontend
      dockerfile: dockerfile
    container_name: Sonic_frontend
    command: bash -c "npm start"
    restart: always
    volumes:
      - ./epresence_frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: ./sonic
      dockerfile: dockerfile
    container_name: Sonic_backend
    command: bash -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./sonic:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  data:
  mysql-db-5.7: