version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: dockerfile_backend
    container_name: Sonic_backend
    command: bash -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/test
    ports:
      - "8000:8000"
    env_file:
      - .env
volumes:
  data: