FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /test

# Install dependencies
COPY requirements.txt /test/
RUN pip install -r requirements.txt

# Copy the project code into the container
COPY . /test/


