FROM python:3.12-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /backend

# MySQL client dependencies
RUN apk add --no-cache mariadb-dev build-base

# mariadb-client is needed for the mysql_config command
RUN apk add --no-cache mariadb-client && addgroup -S mysql && adduser -S mysql -G mysql

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project code into the container
COPY . .

EXPOSE 8000

